name: CI

on:
  pull_request: # Need to run on pull-requests, otherwise PRs from forks don't run
  push:
    branches:
      - master

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Swatinem/rust-cache@v1.3.0
      - uses: dprint/check@v1.5
      - run: cargo clippy --workspace --all-targets -- -D warnings

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: 1.40.0 # MSRV
          override: true
          profile: minimal

      - uses: Swatinem/rust-cache@v1.3.0

      - run: cargo build

  test:
    strategy:
      matrix:
        rust: [
            stable,
            nightly
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal

      - uses: Swatinem/rust-cache@v1.3.0

      - run: cargo test
